### ISSUE TITLE
Docker build image outdated

### ISSUE THREAD

**Issue by BlackDex** [ITRS-Group/geneos-xtender#3]
Hello there,

I'm the maintainer of the build-image you are using.
https://github.com/ITRS-Group/geneos-xtender/blob/37bd7fff2fa6f13422b2434c511902fd48831ed4/Dockerfile#L1

I'm planning on removing the `-openssl3` postfix on the next change (which will be shortly)
Main reason is that only openssl3 is build for a while now.

When updating to a newer version of Rust, i would suggest to also remove the `-openssl3` postfix.

Also, the new images will be using musl v1.2.5.

Cheers.

**Comment by johanthoren** [comment]
@BlackDex, thanks a lot for the notice and have a great day!
